server:
  port: 8941

spring:
  application:
    name: harvest-basic-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10

rocketmq:
  name-server: localhost:9876
  producer:
    group: BASIC-PRODUCER-GROUP
    #发送消息的超时时间
    send-message-timeout: 3000
    #异步消息重试的次数
    retry-times-when-send-async-failed: 2
    #同步消息重试的次数
    retry-times-when-send-failed: 2

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

springfox:
  documentation:
    enabled: false
    auto-startup: false
    swagger-ui:
      enabled: false