server:
  port: 8992

spring:
  application:
    name: harvest-basic-repository
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

logging:
  level:
    com: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl